import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Saludo from '@/components/Saludo'
import Video from '../components/Video.js';
import Audio from '@/components/Audio.js'
import videoData from '../datasource/videodatasources.js'
import audioData from '@/datasource/audiodata.js'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Audio y Video</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1>Video</h1>
        {
          videoData.map(videod => (
            <Video {...videod}> </Video>
          ))
        }
        <br></br>
        <h2>Audio</h2>
        {
          audioData.map(audiod => (
            <Audio {...audiod}> </Audio>
          ))
        }
        
       
      </main>
      <div>

      </div>
      
    </>
  )
}
